"""Deterministic LaTeX tabular rendering."""

from __future__ import annotations

from dimebench.reporting.tables import PaperTable


def escape_latex(value: str) -> str:
    """Escape the subset of LaTeX special characters used in result labels."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def render_latex_table(table: PaperTable, precision: int = 2) -> str:
    """Render a paper table without embedding any result constants."""
    alignment = "ll" + "r" * len(table.columns)
    lines = [
        f"% {table.table_id}; generated by DiME-Bench",
        f"\\begin{{tabular}}{{{alignment}}}",
        "\\toprule",
        "Model & Family & "
        + " & ".join(escape_latex(column) for column in table.columns)
        + r" \\",
        "\\midrule",
    ]
    for row in table.rows:
        values = []
        for column in table.columns:
            cell = row.cells[column]
            values.append(
                "--"
                if cell.scaled_value is None
                else f"{cell.scaled_value:.{precision}f}"
            )
        label = row.model_id
        if row.dataset_id is not None:
            label = f"{label} / {row.dataset_id}"
        lines.append(
            f"{escape_latex(label)} & {escape_latex(row.model_family)} & "
            + " & ".join(values)
            + r" \\"
        )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return "\n".join(lines)
